spring.application.name=gateway_mtz

server.port=8080

# ?? JWT ??????????????????????????????????????????????????????????????
jwt.secret=m1-tiil-a-syst-info-key-32-char-min

# ?? ROUTES ???????????????????????????????????????????????????????????

# Route publique ? Auth (login sans token)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://info-tpsi.univ-brest.fr:10090
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

# Route protégée ? Films
spring.cloud.gateway.routes[1].id=films-service
spring.cloud.gateway.routes[1].uri=http://info-tpsi.univ-brest.fr:10091
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/films/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Route  ? Reviews
spring.cloud.gateway.routes[2].id=reviews-service
spring.cloud.gateway.routes[2].uri=http://localhost:10092
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/reviews/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Route  ? users
spring.cloud.gateway.routes[3].id=users-service
spring.cloud.gateway.routes[3].uri=http://info-tpsi.univ-brest.fr:10045
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# Route  ? reservations
spring.cloud.gateway.routes[4].id=reservation-service
spring.cloud.gateway.routes[4].uri=http://info-tpsi.univ-brest.fr:10056
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/reservations/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

# ?? CORS ?????????????????????????????????????????????????????????????
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[0]=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers[0]=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
